project_id = "wabscwlesbqhxrornsny"

[functions.admin-stats]
verify_jwt = false

[functions.generate-slides]
verify_jwt = false
request_timeout_ms = 400000

[functions.create-payment]
verify_jwt = true